'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BDArtLimpieza

    Partial Public Class Articulos
        Inherits XPLiteObject
        Dim fidArticulo As Integer
        <Key(True)>
        Public Property idArticulo() As Integer
            Get
                Return fidArticulo
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idArticulo), fidArticulo, value)
            End Set
        End Property
        Dim fDescripcion As String
        <Size(50)>
        Public Property Descripcion() As String
            Get
                Return fDescripcion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Descripcion), fDescripcion, value)
            End Set
        End Property
        Dim fStock As Integer
        Public Property Stock() As Integer
            Get
                Return fStock
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Stock), fStock, value)
            End Set
        End Property
        Dim fPrecioUni As Decimal
        Public Property PrecioUni() As Decimal
            Get
                Return fPrecioUni
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(PrecioUni), fPrecioUni, value)
            End Set
        End Property
        Dim fPrecioLista As Decimal
        Public Property PrecioLista() As Decimal
            Get
                Return fPrecioLista
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(PrecioLista), fPrecioLista, value)
            End Set
        End Property
        Dim fStockLoc As Integer
        Public Property StockLoc() As Integer
            Get
                Return fStockLoc
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(StockLoc), fStockLoc, value)
            End Set
        End Property
    End Class

End Namespace
