'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BDArtLimpieza

    Partial Public Class Caja
        Inherits XPLiteObject
        Dim fidCaja As Integer
        <Key(True)>
        Public Property idCaja() As Integer
            Get
                Return fidCaja
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idCaja), fidCaja, value)
            End Set
        End Property
        Dim fApertura As String
        <Size(50)>
        Public Property Apertura() As String
            Get
                Return fApertura
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Apertura), fApertura, value)
            End Set
        End Property
        Dim fCierre As String
        <Size(50)>
        Public Property Cierre() As String
            Get
                Return fCierre
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Cierre), fCierre, value)
            End Set
        End Property
        Dim fTipo As String
        <Size(50)>
        Public Property Tipo() As String
            Get
                Return fTipo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Tipo), fTipo, value)
            End Set
        End Property
        Dim fValor As Decimal
        Public Property Valor() As Decimal
            Get
                Return fValor
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(Valor), fValor, value)
            End Set
        End Property
        Dim fidVenta As Integer
        Public Property idVenta() As Integer
            Get
                Return fidVenta
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idVenta), fidVenta, value)
            End Set
        End Property
        Dim fObservacion As String
        <Size(50)>
        Public Property Observacion() As String
            Get
                Return fObservacion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Observacion), fObservacion, value)
            End Set
        End Property
    End Class

End Namespace
