'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BDArtLimpieza

    Partial Public Class Clientes
        Inherits XPLiteObject
        Dim fidCliente As Integer
        <Key(True)>
        Public Property idCliente() As Integer
            Get
                Return fidCliente
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idCliente), fidCliente, value)
            End Set
        End Property
        Dim fNombre As String
        <Size(50)>
        Public Property Nombre() As String
            Get
                Return fNombre
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Nombre), fNombre, value)
            End Set
        End Property
        Dim fCuit As String
        <Size(50)>
        Public Property Cuit() As String
            Get
                Return fCuit
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Cuit), fCuit, value)
            End Set
        End Property
        Dim fDomicilio As String
        <Size(50)>
        Public Property Domicilio() As String
            Get
                Return fDomicilio
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Domicilio), fDomicilio, value)
            End Set
        End Property
        Dim fLocalidad As String
        <Size(50)>
        Public Property Localidad() As String
            Get
                Return fLocalidad
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Localidad), fLocalidad, value)
            End Set
        End Property
        Dim fTelefono As String
        <Size(50)>
        Public Property Telefono() As String
            Get
                Return fTelefono
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Telefono), fTelefono, value)
            End Set
        End Property
        Dim fMail As String
        <Size(50)>
        Public Property Mail() As String
            Get
                Return fMail
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Mail), fMail, value)
            End Set
        End Property
    End Class

End Namespace
