'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BDArtLimpieza

    Partial Public Class DetallePago
        Inherits XPLiteObject
        Dim fidDetalle As Integer
        <Key(True)>
        Public Property idDetalle() As Integer
            Get
                Return fidDetalle
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idDetalle), fidDetalle, value)
            End Set
        End Property
        Dim fidVenta As Integer
        Public Property idVenta() As Integer
            Get
                Return fidVenta
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idVenta), fidVenta, value)
            End Set
        End Property
        Dim fMedioPago As String
        <Size(50)>
        Public Property MedioPago() As String
            Get
                Return fMedioPago
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(MedioPago), fMedioPago, value)
            End Set
        End Property
        Dim fBanco As String
        <Size(50)>
        Public Property Banco() As String
            Get
                Return fBanco
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Banco), fBanco, value)
            End Set
        End Property
        Dim fTipoTarjeta As String
        <Size(50)>
        Public Property TipoTarjeta() As String
            Get
                Return fTipoTarjeta
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(TipoTarjeta), fTipoTarjeta, value)
            End Set
        End Property
        Dim fNroTarjeta As String
        <Size(50)>
        Public Property NroTarjeta() As String
            Get
                Return fNroTarjeta
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(NroTarjeta), fNroTarjeta, value)
            End Set
        End Property
        Dim fFechaVto As String
        <Size(50)>
        Public Property FechaVto() As String
            Get
                Return fFechaVto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FechaVto), fFechaVto, value)
            End Set
        End Property
        Dim fTitular As String
        <Size(50)>
        Public Property Titular() As String
            Get
                Return fTitular
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Titular), fTitular, value)
            End Set
        End Property
        Dim fTipoCheque As String
        <Size(50)>
        Public Property TipoCheque() As String
            Get
                Return fTipoCheque
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(TipoCheque), fTipoCheque, value)
            End Set
        End Property
        Dim fFechaEmision As String
        <Size(50)>
        Public Property FechaEmision() As String
            Get
                Return fFechaEmision
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FechaEmision), fFechaEmision, value)
            End Set
        End Property
        Dim fFechaCobro As String
        <Size(50)>
        Public Property FechaCobro() As String
            Get
                Return fFechaCobro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FechaCobro), fFechaCobro, value)
            End Set
        End Property
    End Class

End Namespace
