'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BDArtLimpieza

    Partial Public Class DetalleVentas
        Inherits XPLiteObject
        Dim fidDetalle As Integer
        <Key(True)>
        Public Property idDetalle() As Integer
            Get
                Return fidDetalle
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idDetalle), fidDetalle, value)
            End Set
        End Property
        Dim fidVenta As Integer
        Public Property idVenta() As Integer
            Get
                Return fidVenta
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idVenta), fidVenta, value)
            End Set
        End Property
        Dim fArticulo As String
        <Size(50)>
        Public Property Articulo() As String
            Get
                Return fArticulo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Articulo), fArticulo, value)
            End Set
        End Property
        Dim fCantidad As Integer
        Public Property Cantidad() As Integer
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Cantidad), fCantidad, value)
            End Set
        End Property
        Dim fPrecioUni As Decimal
        Public Property PrecioUni() As Decimal
            Get
                Return fPrecioUni
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(PrecioUni), fPrecioUni, value)
            End Set
        End Property
        Dim fPrecioTot As Decimal
        Public Property PrecioTot() As Decimal
            Get
                Return fPrecioTot
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(PrecioTot), fPrecioTot, value)
            End Set
        End Property
    End Class

End Namespace
