'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Namespace BDArtLimpieza

    Partial Public Class Ventas
        Inherits XPLiteObject
        Dim fidVenta As Integer
        <Key(True)>
        Public Property idVenta() As Integer
            Get
                Return fidVenta
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(idVenta), fidVenta, value)
            End Set
        End Property
        Dim fFecha As String
        <Size(50)>
        Public Property Fecha() As String
            Get
                Return fFecha
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Fecha), fFecha, value)
            End Set
        End Property
        Dim fCantidad As Integer
        Public Property Cantidad() As Integer
            Get
                Return fCantidad
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Cantidad), fCantidad, value)
            End Set
        End Property
        Dim fImporteTotal As Decimal
        Public Property ImporteTotal() As Decimal
            Get
                Return fImporteTotal
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ImporteTotal), fImporteTotal, value)
            End Set
        End Property
        Dim fValorPago As Decimal
        Public Property ValorPago() As Decimal
            Get
                Return fValorPago
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ValorPago), fValorPago, value)
            End Set
        End Property
        Dim fCambio As Decimal
        Public Property Cambio() As Decimal
            Get
                Return fCambio
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(Cambio), fCambio, value)
            End Set
        End Property
        Dim fMedioPago As String
        <Size(50)>
        Public Property MedioPago() As String
            Get
                Return fMedioPago
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(MedioPago), fMedioPago, value)
            End Set
        End Property
        Dim fRecargo As String
        <Size(50)>
        Public Property Recargo() As String
            Get
                Return fRecargo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Recargo), fRecargo, value)
            End Set
        End Property
        Dim fObservacion As String
        <Size(50)>
        Public Property Observacion() As String
            Get
                Return fObservacion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Observacion), fObservacion, value)
            End Set
        End Property
        Dim fTipoFactura As String
        <Size(50)>
        Public Property TipoFactura() As String
            Get
                Return fTipoFactura
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(TipoFactura), fTipoFactura, value)
            End Set
        End Property
        Dim fRemito As Integer
        <Size(50)>
        Public Property Remito() As Integer
            Get
                Return fRemito
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Remito), fRemito, value)
            End Set
        End Property
        Dim fCliente As String
        <Size(50)>
        Public Property Cliente() As String
            Get
                Return fCliente
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Cliente), fCliente, value)
            End Set
        End Property
        Dim fUsuario As String
        <Size(50)>
        Public Property Usuario() As String
            Get
                Return fUsuario
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Usuario), fUsuario, value)
            End Set
        End Property
        Dim fNotaCredito As Integer
        Public Property NotaCredito() As Integer
            Get
                Return fNotaCredito
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NotaCredito), fNotaCredito, value)
            End Set
        End Property
    End Class

End Namespace
